name: log name and age
on: push
env:
  name: 'yachao'
  age: 8
  
jobs:
  jobname:
    runs-on: ubuntu-latest
    steps:
      - name: echo avaiale
        run: echo '${{ env.name }} ${{ toJSON(env.age) }}'
        env:
          name: 'shenmin'
      
